# Generated by Django 4.0.4 on 2022-07-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название сайта')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок сайта')),
                ('description', models.CharField(max_length=500, verbose_name='Описание сайта')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[400, 350], upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(max_length=255, verbose_name='Комментарий к посту')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название контакта')),
                ('contact_url', models.URLField(verbose_name='Ссылка на контакт')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'unique_together': {('name', 'contact_url')},
            },
        ),
    ]
